"""Regression coverage for #55: a release rebuild must become the next TM baseline.

The rebuild path can reuse parent checkpoint translations without calling the Provider.
That is correct for cost and safety, but a successful *release* must also make the
machine translations it actually ships formal in SQLite TM.  Preview reuse alone must
remain non-authoritative.
"""
from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from localizer.application.local_build import BuildMode

from tests.test_rebuild_from_run import (
    CHILD,
    PARENT,
    _CountingProvider,
    _Project,
)


class ReleaseRebuildTMPromotionTests(unittest.TestCase):
    def setUp(self) -> None:
        self._temp = tempfile.TemporaryDirectory()
        self.project = _Project(Path(self._temp.name))

    def tearDown(self) -> None:
        self._temp.cleanup()

    def _preview_parent(self, *, fail=()):
        provider = _CountingProvider(fail=fail)
        result = self.project.runner(provider).run(
            mode=BuildMode.PREVIEW,
            run_id=PARENT,
        )
        return provider, result

    def test_zero_provider_release_rebuild_promotes_reused_parent_candidates(self) -> None:
        """The exact production failure: preview -> zero-work release -> fresh plan."""
        parent_provider, parent = self._preview_parent()
        self.assertEqual(4, len(set(parent_provider.requested)))
        self.assertEqual(4, parent.machine_successes)

        before = self.project.runner(_CountingProvider()).plan()
        self.assertEqual(0, before.tm_hits)
        self.assertEqual(4, len(before.pending))

        release_provider = _CountingProvider()
        release = self.project.runner(release_provider).rebuild_from_run(
            PARENT,
            mode=BuildMode.RELEASE,
            run_id=CHILD,
        )
        self.assertEqual([], release_provider.requested)
        self.assertEqual(4, len(release.rebuild.reused))
        # Keep this metric truthful: these were reused, not newly generated by Provider.
        self.assertEqual(0, release.machine_successes)
        self.assertIsNotNone(release.build.bundle)

        after = self.project.runner(_CountingProvider()).plan()
        self.assertEqual(4, after.tm_hits)
        self.assertEqual(0, len(after.pending))

    def test_mixed_reuse_and_retry_are_both_formal_after_release(self) -> None:
        """Reused parent successes and current-run retries must converge into one baseline."""
        _provider, parent = self._preview_parent(fail=("a",))
        self.assertEqual(1, parent.failed_units)

        release_provider = _CountingProvider()
        release = self.project.runner(release_provider).rebuild_from_run(
            PARENT,
            mode=BuildMode.RELEASE,
            run_id=CHILD,
        )
        self.assertEqual([self.project.identity("a")], release_provider.requested)
        self.assertEqual(3, len(release.rebuild.reused))
        self.assertEqual(1, release.machine_successes)

        after = self.project.runner(_CountingProvider()).plan()
        self.assertEqual(4, after.tm_hits)
        self.assertEqual(0, len(after.pending))

    def test_preview_rebuild_does_not_make_reused_candidates_formal(self) -> None:
        """Do not fix #55 by silently treating arbitrary preview machine rows as authority."""
        self._preview_parent()
        child_provider = _CountingProvider()
        child = self.project.runner(child_provider).rebuild_from_run(
            PARENT,
            mode=BuildMode.PREVIEW,
            run_id=CHILD,
        )
        self.assertEqual([], child_provider.requested)
        self.assertEqual(4, len(child.rebuild.reused))

        fresh = self.project.runner(_CountingProvider()).plan()
        self.assertEqual(0, fresh.tm_hits)
        self.assertEqual(4, len(fresh.pending))


if __name__ == "__main__":
    unittest.main()
